### ISSUE TITLE
Use conditional get when fetching data

### ISSUE THREAD

**Issue by simonw** [simonw/coronavirus-data-gov-archive#1]
Suggestion by https://twitter.com/dracos/status/1255221799085846532

**Comment by simonw** [comment]
Curl added ETags support a few months ago: https://daniel.haxx.se/blog/2019/12/06/curl-speaks-etag/

I installed a compatible version of curl on macOS using:

```
brew install curl
echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.zshrc
```
Now I get this:
```
% curl --version
curl 7.69.1 (x86_64-apple-darwin19.3.0) libcurl/7.69.1 SecureTransport zlib/1.2.11
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```
GitHub Actions is running an older `curl` version though: https://github.com/simonw/playing-with-actions/runs/627365543?check_suite_focus=true
```
Run curl --version
  curl --version
  shell: /bin/bash -e {0}
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Comment by simonw** [comment]
Not sure what the best option for getting curl 7.68.0 or higher in a GitHub Action is.

**Comment by dracos** [comment]
You could just specify the header manually with -H yourself? :) `-H"If-None-Match: etag"` - but where will you get the etag from

**Comment by stuartlangridge** [comment]
`curl --head ...data_latest.json | grep etag | awk '{gsub(/"/,"",$2); print $2}' > data_latest.etag`, no? And then put `-H"If-None-Match: $(cat data_latest.etag)` in the actual fetch command?

**Comment by dracos** [comment]
I wasn't sure if it had access to data from the last run, but yes you could just commit it along with everything else couldn't you. I just use the mtime because I have this old school persistence thing going on ;)

**Comment by simonw** [comment]
I think I've managed to use a GitHub Action to compile a standalone `curl` 7.69.1 binary which I can copy into this repo and use directly... https://github.com/simonw/playing-with-actions/commits/master/.github/workflows/latest-curl.yml

**Comment by simonw** [comment]
Yes! I think this is going to work: https://github.com/simonw/coronavirus-data-gov-archive/runs/627888901

<img width="956" alt="Show_curl_--version__refs__1_·_simonw_coronavirus-data-gov-archive_15a35c8" src="https://user-images.githubusercontent.com/9599/80548869-9b1e0600-8970-11ea-99f4-6d2c034adeff.png">

**Comment by simonw** [comment]
I got stuck on a possible bug in curl, reported over here: https://github.com/curl/curl/issues/5309

**Comment by simonw** [comment]
Maybe I can use `--time-cond` instead? https://ec.haxx.se/http/http-requests#time-conditions

**Comment by simonw** [comment]
This seems to be working: https://github.com/simonw/coronavirus-data-gov-archive/runs/628412270

I'll close this ticket after I've seen it pick up some changes.

**Comment by dracos** [comment]
Won't the time stamp of the files be the time you checked out the repo, not the time the file was checked in? Running the below at 07:38:35 this morning:
```
$ git clone https://github.com/simonw/coronavirus-data-gov-archive
$ cd coronavirus-data-gov-archive
$ perl -e'print join " ", stat "data_latest.json";'
14 5910974511248224 33204 1 1000 1000 0 3365400 1588142315 1588142315 1588142315 512 6576⏎
$ perl -e'print scalar localtime 1588142315'
Wed Apr 29 07:38:35 2020⏎
```
So if the file got changed between your runs, you'd miss the change, because your file's timestamp would be later than the remote file's.
Saving the etag on fetch in the repo then using that with `curl -H"If-None-Match: etag"` seems the easiest way to go to me.

**Comment by hubgit** [comment]
I think you'll probably want to store the original downloaded file (with the correct remote timestamp) and the jq-processed version separately, like [this](https://github.com/hubgit/coronavirus-data-gov-archive/blob/2641c0728b58ed6afc2d9d2c0fcb427d325f9020/scripts/update.sh).

**Comment by dracos** [comment]
That still won't help with knowing the timestamp (or etag) to use for the next request, because git does not maintain timestamps.

**Comment by hubgit** [comment]
> That still won't help with knowing the timestamp (or etag) to use for the next request, because git does not maintain timestamps.

Ah, you're right - etag does sound best then.

**Comment by hubgit** [comment]
I was able to get this working by calling out to an ETag-capable curl in a separate GitHub Action, with the file and URL as parameters:

* https://github.com/hubgit/curl-etag/blob/master/curl-etag
* https://github.com/hubgit/coronavirus-data-gov-archive/blob/master/.github/workflows/scheduled.yml

**Comment by simonw** [comment]
I gave up on curl and wrote a little custom tool, https://github.com/simonw/conditional-get

Just ran for the first time - the first batch of etags have now been committed to the repo here: https://github.com/simonw/coronavirus-data-gov-archive/blob/abc0ac74f38b0d75ccae2f71a7cacd19b03563b0/etags.json

**Comment by simonw** [comment]
Hah, in the time it took me to write `conditional-get` a new version of curl, `7.70.0`, came out with a fix for that bug! And @hubgit figured out a workaround.

**Comment by simonw** [comment]
https://github.com/simonw/coronavirus-data-gov-archive/runs/630462572?check_suite_focus=true shows that `conditional-get` is working:

<img width="867" alt="Added_badge_·_simonw_coronavirus-data-gov-archive_0ac898b" src="https://user-images.githubusercontent.com/9599/80626346-26e07280-8a03-11ea-9e7a-7036a471daf3.png">

I'm going to close this now. Will maybe revisit once `curl 7.70.0` is more easily available in GitHub Action workers!

**Comment by simonw** [comment]
I compiled a standalone curl 7.70.0 binary for use in GitHub Actions here: https://github.com/simonw/playing-with-actions/blob/master/curl - downloading that binary should allow using the latest curl in any action.

Here's the workflow that compiled it: https://github.com/simonw/playing-with-actions/blob/248d1ddccb87f9f0da2a3b0a95633fcb8eded650/.github/workflows/latest-curl.yml
